nav:
  - Home: 'index.md'
  - About CS1010: 'about.md'
  - Notes: 
    - 1. What is a Program?: "01-program.md"
    - 2. Computational Problem & Algorithms: "02-algo.md"
    - 3. Functions: "03-func.md"
    - 4. Types: "04-type.md"
  - Learning Outcomes: 'outcomes.md'
  - Schedule: 'schedule.md'
  - Accounts: 'accounts.md'
  - Policies: 'policies.md'
  - Readings: 'readings.md'
  - Software/Tools:
      - Programming Environments: 'environments.md'
      - UNIX: 'unix.md'
      - CLang: 'clang.md'
      - Vim: 'vim.md'
      - Zoom: 'zoom.md'
  - 18/19 Sem 1: '1819s1.md'

# pip install pymdown-extensions
# pip install pygments
site_name: CS1010 Programming Methodology
# repo_url: https://github.com/nus-cs1010/1819-s1
site_url: https://nus-cs1010.github.io/2021-s1
copyright: Copyright by Department of Computer Science, National University of Singapore 2020
# remote_branch: gh-pages
use_directory_urls: false
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
     linenums: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - fontawesome_markdown
        
theme: 
  name: material
  palette:
    primary: teal
  features:
    - instant
  shortcuts:
    previous: 72 #h
    next: 76 #l
    search: 191 #/

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://use.fontawesome.com/releases/v5.14.0/js/all.js

extra_css:
  - 'stylesheets/extra.css'
  - 'https://fonts.googleapis.com/css?family=Roboto:400,700'
  - 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap'
  - 'https://use.fontawesome.com/releases/v5.14.0/css/all.css'
