nav:
  - Home: 'index.md'
  - Notes: 
    - 1. What is a Program?: "01-program.md"
    - 2. Computational Problems: "02-algo.md"
    - 3. Functions: "03-func.md"
    - 4. Types: "04-type.md"
    - 5. First C Program: "05-first-c.md"
    - 6. CS1010 I/O: "06-cs1010-io.md"
    - 7. Arithmetic Operations: "07-arithmetic-ops.md"
    - 8. Conditional Statement: "08-if-else.md"
    - 9. Logical Expression: "09-logical-exp.md"
    - 10. Assertion: "10-assert.md"
    - 11. Loop: "11-loop.md"
    - 12. Invariant: "12-invariant.md"
  - Lab Guides: 
    - Guide to Assignments/Exercises: "assignment.md"
    - Unix:
      - Background: "unix-background.md"
      - Essentials: "unix-essentials.md"
      - Advanced: "unix-advanced.md"
    - Vim:
      - Philosophy: "vim-philosophy.md"
      - Quick Lesson: "vim-quick-lessons.md"
      - Setup: "vim-setup.md"
      - Extensions: "vim-plugins.md"
      - Tips: "vim-tips.md"
    - PE Nodes:
      - Programming Environments: "environments.md"
      - Linking GitHub to PE: "github.md"
      - Using tmate: "tmate.md"
    - C Programming:
      - C in CS1010: 'c-in-cs1010.md'
      - Common Clang Messages: 'messages.md'
      - CS1010 I/O Library: "library.md"
  - Readings: "readings.md"   


theme: 
  name: material
  features: 
    - navigation.instant
    - toc.follow
    - toc.integrate
    - content.code.annotate
  palette:
    primary: deep purple
    accent: deep purple
  shortcuts:
    previous: 72 #h
    next: 76 #l
    search: 191 #/

site_name: CS1010 Programming Methodology
# repo_url: https://github.com/nus-cs1010/1819-s1
site_url: https://nus-cs1010.github.io/2223-s1
copyright: Copyright by Department of Computer Science, National University of Singapore 2022
# remote_branch: gh-pages
use_directory_urls: false
markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.highlight:
     linenums: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map: {
        bang: "!",
        dollar: "$",
        parenthesis-left: "(",
        parenthesis-right: ")",
      }
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - 'stylesheets/extra.css'
  - 'https://fonts.googleapis.com/css?family=Roboto:400,700'
  - 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap'
